// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frqqzmcikpeytksvxexr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZycXF6bWNpa3BleXRrc3Z4ZXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzU5NDksImV4cCI6MjA3NDI1MTk0OX0.Woq0pkCOabrCeqccX1-kGf7A9x77MFld9p12jN2f6pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});